// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/notification_scheduler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:flutter/material.dart' as _i3;
import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i12;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i13;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i15;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i17;
import 'package:flutter_local_notifications/src/types.dart' as _i18;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/controllers/notification_planner.dart' as _i4;
import 'package:mona/data/model/molecule.dart' as _i8;
import 'package:mona/data/model/placement.dart' as _i9;
import 'package:mona/data/model/planned_notification.dart' as _i5;
import 'package:mona/data/model/units.dart' as _i7;
import 'package:mona/services/preferences_service.dart' as _i6;
import 'package:mona/theme/custom_theme_settings.dart' as _i2;
import 'package:timezone/timezone.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCustomThemeSettings_0 extends _i1.SmartFake
    implements _i2.CustomThemeSettings {
  _FakeCustomThemeSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimeOfDay_1 extends _i1.SmartFake implements _i3.TimeOfDay {
  _FakeTimeOfDay_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationPlanner].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationPlanner extends _i1.Mock
    implements _i4.NotificationPlanner {
  @override
  List<_i5.PlannedNotification> planNotifications({required int? daysAhead}) =>
      (super.noSuchMethod(
        Invocation.method(
          #planNotifications,
          [],
          {#daysAhead: daysAhead},
        ),
        returnValue: <_i5.PlannedNotification>[],
        returnValueForMissingStub: <_i5.PlannedNotification>[],
      ) as List<_i5.PlannedNotification>);

  @override
  int daysAhead({required int? maxScheduled}) => (super.noSuchMethod(
        Invocation.method(
          #daysAhead,
          [],
          {#maxScheduled: maxScheduled},
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i6.PreferencesService {
  @override
  bool get customThemeEnabled => (super.noSuchMethod(
        Invocation.getter(#customThemeEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.CustomThemeSettings get customTheme => (super.noSuchMethod(
        Invocation.getter(#customTheme),
        returnValue: _FakeCustomThemeSettings_0(
          this,
          Invocation.getter(#customTheme),
        ),
        returnValueForMissingStub: _FakeCustomThemeSettings_0(
          this,
          Invocation.getter(#customTheme),
        ),
      ) as _i2.CustomThemeSettings);

  @override
  bool get autoCheckUpdatesEnabled => (super.noSuchMethod(
        Invocation.getter(#autoCheckUpdatesEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get notificationsEnabled => (super.noSuchMethod(
        Invocation.getter(#notificationsEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Units get units => (super.noSuchMethod(
        Invocation.getter(#units),
        returnValue: _i7.Units.pg_mL_ng_dL,
        returnValueForMissingStub: _i7.Units.pg_mL_ng_dL,
      ) as _i7.Units);

  @override
  _i7.EstradiolUnit get estradiolUnit => (super.noSuchMethod(
        Invocation.getter(#estradiolUnit),
        returnValue: _i7.EstradiolUnit.pg_mL,
        returnValueForMissingStub: _i7.EstradiolUnit.pg_mL,
      ) as _i7.EstradiolUnit);

  @override
  _i7.TestosteroneUnit get testosteroneUnit => (super.noSuchMethod(
        Invocation.getter(#testosteroneUnit),
        returnValue: _i7.TestosteroneUnit.ng_dL,
        returnValueForMissingStub: _i7.TestosteroneUnit.ng_dL,
      ) as _i7.TestosteroneUnit);

  @override
  List<_i8.Molecule> get customMolecules => (super.noSuchMethod(
        Invocation.getter(#customMolecules),
        returnValue: <_i8.Molecule>[],
        returnValueForMissingStub: <_i8.Molecule>[],
      ) as List<_i8.Molecule>);

  @override
  List<_i8.Molecule> get allMolecules => (super.noSuchMethod(
        Invocation.getter(#allMolecules),
        returnValue: <_i8.Molecule>[],
        returnValueForMissingStub: <_i8.Molecule>[],
      ) as List<_i8.Molecule>);

  @override
  List<_i9.Placement> get placementsList => (super.noSuchMethod(
        Invocation.getter(#placementsList),
        returnValue: <_i9.Placement>[],
        returnValueForMissingStub: <_i9.Placement>[],
      ) as List<_i9.Placement>);

  @override
  List<int> get scheduleOrder => (super.noSuchMethod(
        Invocation.getter(#scheduleOrder),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  bool get placementSuggestionPerSchedule => (super.noSuchMethod(
        Invocation.getter(#placementSuggestionPerSchedule),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hrtCounterEnabled => (super.noSuchMethod(
        Invocation.getter(#hrtCounterEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get slimeModeEnabled => (super.noSuchMethod(
        Invocation.getter(#slimeModeEnabled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get logicalDayStartMinutesRaw => (super.noSuchMethod(
        Invocation.getter(#logicalDayStartMinutesRaw),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i3.TimeOfDay get logicalDayStart => (super.noSuchMethod(
        Invocation.getter(#logicalDayStart),
        returnValue: _FakeTimeOfDay_1(
          this,
          Invocation.getter(#logicalDayStart),
        ),
        returnValueForMissingStub: _FakeTimeOfDay_1(
          this,
          Invocation.getter(#logicalDayStart),
        ),
      ) as _i3.TimeOfDay);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i10.Future<void> setCustomThemeEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomThemeEnabled,
          [isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setCustomTheme(_i2.CustomThemeSettings? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomTheme,
          [value],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setAutoCheckUpdatesEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoCheckUpdatesEnabled,
          [isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setNotificationsEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsEnabled,
          [isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setSavedLanguageTag(String? code) => (super.noSuchMethod(
        Invocation.method(
          #setSavedLanguageTag,
          [code],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setEstradiolUnit(_i7.EstradiolUnit? unit) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEstradiolUnit,
          [unit],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setTestosteroneUnit(_i7.TestosteroneUnit? unit) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTestosteroneUnit,
          [unit],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> addCustomMolecule(_i8.Molecule? molecule) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomMolecule,
          [molecule],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> removeCustomMolecule(String? name) => (super.noSuchMethod(
        Invocation.method(
          #removeCustomMolecule,
          [name],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setPlacementsList(List<_i9.Placement>? placements) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlacementsList,
          [placements],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setScheduleOrder(List<int>? order) => (super.noSuchMethod(
        Invocation.method(
          #setScheduleOrder,
          [order],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setPlacementSuggestionPerSchedule(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPlacementSuggestionPerSchedule,
          [isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setHrtCounterEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHrtCounterEnabled,
          [isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setSlimeModeEnabled(bool? isEnabled) => (super.noSuchMethod(
        Invocation.method(
          #setSlimeModeEnabled,
          [isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> setLogicalDayStart(_i3.TimeOfDay? time) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLogicalDayStart,
          [time],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i12.FlutterLocalNotificationsPlugin {
  @override
  _i10.Future<bool?> initialize({
    required _i13.InitializationSettings? settings,
    _i14.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i14.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #settings: settings,
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i10.Future<bool?>.value(),
        returnValueForMissingStub: _i10.Future<bool?>.value(),
      ) as _i10.Future<bool?>);

  @override
  _i10.Future<_i14.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue:
                _i10.Future<_i14.NotificationAppLaunchDetails?>.value(),
            returnValueForMissingStub:
                _i10.Future<_i14.NotificationAppLaunchDetails?>.value(),
          ) as _i10.Future<_i14.NotificationAppLaunchDetails?>);

  @override
  _i10.Future<void> show({
    required int? id,
    String? title,
    String? body,
    _i15.NotificationDetails? notificationDetails,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #notificationDetails: notificationDetails,
            #payload: payload,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancel({
    required int? id,
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {
            #id: id,
            #tag: tag,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> zonedSchedule({
    required int? id,
    required _i16.TZDateTime? scheduledDate,
    required _i15.NotificationDetails? notificationDetails,
    required _i17.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
    _i18.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [],
          {
            #id: id,
            #scheduledDate: scheduledDate,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> periodicallyShow({
    required int? id,
    required _i14.RepeatInterval? repeatInterval,
    required _i15.NotificationDetails? notificationDetails,
    required _i17.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [],
          {
            #id: id,
            #repeatInterval: repeatInterval,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> periodicallyShowWithDuration({
    required int? id,
    required Duration? repeatDurationInterval,
    required _i15.NotificationDetails? notificationDetails,
    String? title,
    String? body,
    _i17.AndroidScheduleMode? androidScheduleMode =
        _i17.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [],
          {
            #id: id,
            #repeatDurationInterval: repeatDurationInterval,
            #notificationDetails: notificationDetails,
            #title: title,
            #body: body,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i14.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue:
                _i10.Future<List<_i14.PendingNotificationRequest>>.value(
                    <_i14.PendingNotificationRequest>[]),
            returnValueForMissingStub:
                _i10.Future<List<_i14.PendingNotificationRequest>>.value(
                    <_i14.PendingNotificationRequest>[]),
          ) as _i10.Future<List<_i14.PendingNotificationRequest>>);

  @override
  _i10.Future<List<_i14.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i10.Future<List<_i14.ActiveNotification>>.value(
            <_i14.ActiveNotification>[]),
        returnValueForMissingStub:
            _i10.Future<List<_i14.ActiveNotification>>.value(
                <_i14.ActiveNotification>[]),
      ) as _i10.Future<List<_i14.ActiveNotification>>);
}
