// Mocks generated by Mockito 5.4.6 from annotations
// in mona/test/controllers/slots_builder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mona/data/model/date.dart' as _i8;
import 'package:mona/data/model/graph_calculator.dart' as _i7;
import 'package:mona/data/model/medication_intake.dart' as _i5;
import 'package:mona/data/model/medication_schedule.dart' as _i11;
import 'package:mona/data/providers/medication_intake_provider.dart' as _i4;
import 'package:mona/data/providers/medication_schedule_provider.dart' as _i10;
import 'package:mona/services/preferences_service.dart' as _i3;
import 'package:mona/services/repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRepository_0<T> extends _i1.SmartFake implements _i2.Repository<T> {
  _FakeRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferencesService_1 extends _i1.SmartFake
    implements _i3.PreferencesService {
  _FakePreferencesService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationIntakeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeProvider extends _i1.Mock
    implements _i4.MedicationIntakeProvider {
  @override
  _i2.Repository<_i5.MedicationIntake> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i5.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i5.MedicationIntake>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i5.MedicationIntake>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i5.MedicationIntake> get intakes => (super.noSuchMethod(
        Invocation.getter(#intakes),
        returnValue: <_i5.MedicationIntake>[],
        returnValueForMissingStub: <_i5.MedicationIntake>[],
      ) as List<_i5.MedicationIntake>);

  @override
  List<_i5.MedicationIntake> get takenIntakesSortedDesc => (super.noSuchMethod(
        Invocation.getter(#takenIntakesSortedDesc),
        returnValue: <_i5.MedicationIntake>[],
        returnValueForMissingStub: <_i5.MedicationIntake>[],
      ) as List<_i5.MedicationIntake>);

  @override
  List<_i5.MedicationIntake> get takenIntakes => (super.noSuchMethod(
        Invocation.getter(#takenIntakes),
        returnValue: <_i5.MedicationIntake>[],
        returnValueForMissingStub: <_i5.MedicationIntake>[],
      ) as List<_i5.MedicationIntake>);

  @override
  List<_i5.MedicationIntake> get notTakenIntakes => (super.noSuchMethod(
        Invocation.getter(#notTakenIntakes),
        returnValue: <_i5.MedicationIntake>[],
        returnValueForMissingStub: <_i5.MedicationIntake>[],
      ) as List<_i5.MedicationIntake>);

  @override
  List<_i5.MedicationIntake> get plottableIntakes => (super.noSuchMethod(
        Invocation.getter(#plottableIntakes),
        returnValue: <_i5.MedicationIntake>[],
        returnValueForMissingStub: <_i5.MedicationIntake>[],
      ) as List<_i5.MedicationIntake>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i5.MedicationIntake> getTakenIntakesDescForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesDescForSchedule,
          [scheduleId],
        ),
        returnValue: <_i5.MedicationIntake>[],
        returnValueForMissingStub: <_i5.MedicationIntake>[],
      ) as List<_i5.MedicationIntake>);

  @override
  _i6.Future<void> fetchIntakes() => (super.noSuchMethod(
        Invocation.method(
          #fetchIntakes,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteIntakeFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntakeFromId,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteIntake(_i5.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [intake],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> add(_i5.MedicationIntake? intake) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [intake],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateIntake(_i5.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIntake,
          [intake],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i7.GraphIntake> getIntakesForGraph(DateTime? tMin) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntakesForGraph,
          [tMin],
        ),
        returnValue: <_i7.GraphIntake>[],
        returnValueForMissingStub: <_i7.GraphIntake>[],
      ) as List<_i7.GraphIntake>);

  @override
  _i8.Date? getLastIntakeLocalDateFromList(
          List<_i5.MedicationIntake>? intakes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeLocalDateFromList,
          [intakes],
        ),
        returnValueForMissingStub: null,
      ) as _i8.Date?);

  @override
  _i8.Date? getLastIntakeLocalDateForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastIntakeLocalDateForSchedule,
          [scheduleId],
        ),
        returnValueForMissingStub: null,
      ) as _i8.Date?);

  @override
  List<_i5.MedicationIntake> getTakenIntakesForScheduleOn(
    int? scheduleId,
    _i8.Date? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTakenIntakesForScheduleOn,
          [
            scheduleId,
            date,
          ],
        ),
        returnValue: <_i5.MedicationIntake>[],
        returnValueForMissingStub: <_i5.MedicationIntake>[],
      ) as List<_i5.MedicationIntake>);

  @override
  _i5.MedicationIntake? getLastTakenIntakeForSchedule(int? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastTakenIntakeForSchedule,
          [scheduleId],
        ),
        returnValueForMissingStub: null,
      ) as _i5.MedicationIntake?);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MedicationScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationScheduleProvider extends _i1.Mock
    implements _i10.MedicationScheduleProvider {
  @override
  _i2.Repository<_i11.MedicationSchedule> get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRepository_0<_i11.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeRepository_0<_i11.MedicationSchedule>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.Repository<_i11.MedicationSchedule>);

  @override
  _i3.PreferencesService get preferences => (super.noSuchMethod(
        Invocation.getter(#preferences),
        returnValue: _FakePreferencesService_1(
          this,
          Invocation.getter(#preferences),
        ),
        returnValueForMissingStub: _FakePreferencesService_1(
          this,
          Invocation.getter(#preferences),
        ),
      ) as _i3.PreferencesService);

  @override
  List<_i11.MedicationSchedule> get schedules => (super.noSuchMethod(
        Invocation.getter(#schedules),
        returnValue: <_i11.MedicationSchedule>[],
        returnValueForMissingStub: <_i11.MedicationSchedule>[],
      ) as List<_i11.MedicationSchedule>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i11.MedicationSchedule? getScheduleById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getScheduleById,
          [id],
        ),
        returnValueForMissingStub: null,
      ) as _i11.MedicationSchedule?);

  @override
  _i6.Future<void> fetchSchedules() => (super.noSuchMethod(
        Invocation.method(
          #fetchSchedules,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> reorder(
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorder,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteScheduleFromId(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleFromId,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteSchedule(_i11.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSchedule,
          [schedule],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> add(_i11.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [schedule],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateSchedule(_i11.MedicationSchedule? schedule) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedule],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
